/* ==========================================================
   OXXO ADMIN - ALIAS DE COLUMNAS
   Mantiene equivalencias de encabezados por dashboard para
   validar archivos Excel sin tocar la logica principal.
   ========================================================== */

window.OXXO_ADMIN_COLUMN_ALIASES = {
    'Plaza':['plaza','plazas','nombre plaza'],'Plazas':['plazas','plaza','nombre plaza'],'Bajas Plaza':['bajas plaza','bajas_plaza','total bajas'],'Asesor':['asesor','at','at ro','at/ro','asesor at','nombre asesor','responsable'],'Unidad org':['unidad org','unidad org.','unidad org/','unidad organizativa','texto breve de unidad organizativa','tienda','nombre tienda'],'CR TIENDA':['cr tienda','cr de tienda','cr','id tienda','crtienda'],'ID posiciones':['id posiciones','id posicion','id position','posicion','id puesto'],'Descripcion de Posicion':['descripcion de posicion','denominacion posicion','puesto','descripcion puesto','puestos homologados'],'Status ocupacion':['status ocupacion','estatus ocupacion','status de ocupacion','estado ocupacion'],'Fecha':['fecha','f. validez','f validez','f.crea','f crea','fecha crea','fecha creacion','status ocupacion'],'Dias Vacantes':['dias vacantes','dias vacante','dias','dias de vacante','antiguedad'],'Mes':['mes','periodo','mes semana'],'Empleados':['empleados','empleado','nombre del empleado','nombre empleado','nombre del empleado o candidato'],'Semana':['semana','sem','mes semana','semana de baja'],'Temporalidad':['temporalidad','tipo temporalidad'],'Rot_Temp':['rot temp','rot_temp','rotacion temporal','rot. temprana','rot temprana'],'Puesto':['puesto','puestos homologados','descripcion de posicion','denominacion posicion','posicion','funcion','denominacion funcion actual'],'Nombre del empleado':['nombre del empleado','empleado','nombre empleado','nombre del empleado o candidato'],'No Personal':['n pers','nÃ‚Â° pers.','no personal','numero personal','numero de personal','n de personal'],'Motivo':['motivo','denominacion motivo'],'Detalle':['detalle de baja','detalle baja','comentarios'],'Edad':['edad'],'Genero':['genero','sexo'],
    'Denominacion Medida':['denominacion medida','medida','med.'],'Denominacion Motivo':['denominacion motivo','motivo'],'Denominacion Posicion Anterior':['denominacion posicion anterior','puesto anterior','posicion anterior'],'Denominacion Posicion Actual':['denominacion posicion actual','puesto actual','posicion actual'],'Denominacion Funcion Anterior':['denominacion funcion anterior','funcion anterior'],'Denominacion Funcion Actual':['denominacion funcion actual','funcion actual'],'Denominacion U.Org. Actual':['denominacion u org actual','denominacion u org act','denominacion u organ actual'],'F.Crea':['f.crea','f crea','fecha crea','fecha','f. crea.'],
    'Tienda':['tienda','unidad org','unidad org.','texto breve de unidad organizativa','denominacion u org actual','nombre tienda'],'UO':['uo','un.org.','unidad organizativa'],'Estructura Diaria':['estructura diaria','estructura_diaria','estructura'],'AUSENTISMOS':['ausentismos','aus no justificado'],'Vacante':['vacante','% vacantes'],'LIDER':['lider'],'ENCARGADO':['encargado'],'AYUDANTE':['ayudante'],'Vacantes':['vacantes','vacantes totales'],'Aprovechamiento Estructura':['aprovechamiento estructura','aprovechamiento de estructura','% aprovechamiento','aprovechamiento'],'Estatus Con impacto Ausentismo':['estatus con impacto ausentismo','estatus','clas aprov','clasificacion aprovechamiento'],'EC SIN AUSENTISMO':['ec sin ausentismo'],'FECHA':['fecha','corte'],
    'Zona':['zona'],'Region':['region','regiÃƒÂ³n'],'Numero de personal':['numero de personal','n de personal','no personal','nÃ‚Â° de personal'],'Nombre del empleado o candidato':['nombre del empleado o candidato','nombre del empleado','empleado','nombre'],'Esquema':['esquema'],'Textos homologados':['textos homologados','texto homologado','concepto'],'Texto breve de unidad organizativa':['texto breve de unidad organizativa','tienda'],'Cr de Tienda':['cr de tienda','cr tienda','cr'],'Cantidad':['cantidad','horas'],'Importe':['importe','gasto','gasto $'],'Ano':['ano','aÃƒÂ±o'],
    'Area':['area de personal'],'No. De Empleado':['no. de empleado','no de empleado','numero empleado','n empleado'],'Nombre':['nombre','nombre empleado'],'Fecha_Inicio':['fechas de aniversario inicio','fecha_inicio','fecha inicio','inicio'],'Fecha_Fin':['fechas de aniversario fin','fecha_fin','fecha fin','fin'],'Periodo_Anterior':['dias restantes per ant','periodo anterior'],'Periodo_Actual':['dias restantes per act','periodo actual'],'Dias_Restantes':['total dias restantes','total dÃƒÂ­as restantes','dias restantes'],'Total dias restantes':['total dias restantes','total dÃƒÂ­as restantes'],'Bucket_Ant':['meses para disfrutar vacaciones de per ant','meses para disfrutar vacaciones de per. ant.'],'Bucket_Act':['meses para disfrutar vacaciones de per act','meses para disfrutar vacaciones de per. act'],'Tipo de Conting.':['tipo de conting','tipo de conting.'],'Posicion':['posicion','posiciÃƒÂ³n'],
    'N de personal':['n de personal','nÃ‚Â° de personal','numero de personal'],'Estatus':['estatus'],'Tipo_Ausentismo':['texto infotipo','tipo ausentismo','ausentismo'],'Denominacion':['denominacion'],'Inicio de validez':['inicio de validez'],'Fin de validez':['fin de validez'],'Dias':['dias presenc abs','dÃƒÂ­as presenc./abs.','dias'],'Horas':['horas de presencia','horas'],'Absentismos solo en la semana':['absentismos solo en la semana'],'Inicio de semana':['inicio de semana'],'Fin de semana':['fin de semana'],
    'CR Reg':['cr reg'],'ID Tienda':['id tienda'],'Accionable sugerido TREO':['accionable sugerido treo','racional de la estructura'],'TREO':['estructura propuesta treo p2 jun ago','treo','est treo','estructura treo'],'SAP':['estructura sap','sap','est sap','plantilla sap'],'Activos':['empleados activos','activos','empleados','personal activo'],'DIF':['dif sap vs est optima final','dif'],'Movimiento':['movimiento inicial','movimiento','estatus movimiento'],'Turnos':['turnos'],'Antiguedad':['antiguedad','antigÃƒÂ¼edad'],'ASESOR':['asesor','at'],'TIENDA':['tienda','unidad org'],
    'Asesor_Correcto':['asesor_correcto','asesor correcto','asesor'],'Unidad org.':['unidad org.','unidad org','texto breve de unidad organizativa'],'Cr de tienda':['cr de tienda','cr tienda','cr'],'Puesto_Correcto':['puesto_correcto','puesto correcto','puesto'],'Nº personal':['n personal','nÂ° personal','no personal','numero de personal','n de personal'],
    'Promedio de Código de Ética 2026':['promedio de codigo de etica 2026','codigo de etica 2026','codigo de etica'],
    'Promedio de Seguridad en la persona 2026':['promedio de seguridad en la persona 2026','seguridad en la persona 2026','seguridad en la persona'],
    'Promedio de Cobro dls Sedes Mundialistas 2026':['promedio de cobro dls sedes mundialistas 2026','cobro dls sedes mundialistas 2026','cobro dls sedes mundialistas'],
    'Promedio de Capacidad Tablero Amazon Counter':['promedio de capacidad tablero amazon counter','capacidad tablero amazon counter','tablero amazon counter'],
    'Promedio de PLD2026Certificacion':['promedio de pld2026certificacion','pld2026certificacion','pld 2026 certificacion','pld2026 certificacion'],
    'Promedio de ModuloCercaSiempre2026':['promedio de modulocercasiempre2026','modulocercasiempre2026','modulo cerca siempre 2026'],
    'Promedio de Resultado Certificación Alimentos y Bebidas 2026':['promedio de resultado certificacion alimentos y bebidas 2026','resultado certificacion alimentos y bebidas 2026','certificacion alimentos y bebidas'],
    'Pan Horneado':['pan horneado'],
    'CR':['cr'],'Concepto':['faltante sobrante','concepto']
  };